---
abstract: 'Access the Beeminder API'
author:
  - 'Paul Fenwick <pjf@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Beeminder
requires:
  Carp: 0
  JSON::Any: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Method::Signatures: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/pfenwick/WebService-Beeminder.git
version: 0.002
